# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - tombolo-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://hpccsollabacr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_2d56e9976846421ab5836c07eefc1f9d }}
        password: ${{ secrets.AzureAppService_ContainerPassword_32f0500f43ba46739f1398dca9316ce0 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: hpccsollabacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_2d56e9976846421ab5836c07eefc1f9d }}/tombolo-node:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'tombolo-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_03f11bc227e543a8828272eab3705713 }}
        images: 'hpccsollabacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_2d56e9976846421ab5836c07eefc1f9d }}/tombolo-node:${{ github.sha }}'