# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - tombolo-node

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/checkout@v2
    - name: create env file
      run: |
        touch .env
        echo DB_USERNAME=${{ secrets.DB_USERNAME }} >> .env
        echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
        echo DB_PORT=${{ secrets.DB_PORT }} >> .env
        echo DB_NAME=${{ secrets.DB_NAME }} >> .env
        echo DB_HOSTNAME=${{ secrets.DB_HOSTNAME }} >> .env
        echo AUTH_SERVICE_URL=${{ secrets.AUTH_SERVICE_URL }} >> .env
        echo AUTHSERVICE_TOMBOLO_CLIENT_ID=${{ secrets.AUTHSERVICE_TOMBOLO_CLIENT_ID }} >> .env
        echo secret=${{ secrets.secret }} >> .env
      working-directory: server
      
    - name: Rename cluster-whitelist
      run: cp cluster-whitelist.sample.js cluster-whitelist.js
      working-directory: ./server  
      

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://tombolo.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_35f0b2a90d5143a2a32b803aa6b5ad62 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_5105f6e998014001becaa3f64939efbf }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: tombolo.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_35f0b2a90d5143a2a32b803aa6b5ad62 }}/tombolo_node:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'tombolo-node'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_c1492ae7c1c84948aa620130e501fd38 }}
        images: 'tombolo.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_35f0b2a90d5143a2a32b803aa6b5ad62 }}/tombolo_node:${{ github.sha }}'
